title: NetRay Compiler Docs
description: Documentation for the NetRay IDL compiler Studio plugin
url: https://astawastaken.github.io
baseurl: "/NetRay-Compile"
remote_theme: just-the-docs/just-the-docs@v0.8.1
color_scheme: netray
search_enabled: true
heading_anchors: true
permalink: pretty
plugins:
  - jekyll-remote-theme
footer_content: "NetRay Compiler docs. Current supported frontend: Roblox Studio plugin."

defaults:
  - scope:
      path: "assets"
      type: pages
    values:
      layout: null
